### ISSUE TITLE
[Main Page] Fix price block styles

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#10]
Fix price block styles

![m5](https://user-images.githubusercontent.com/9034705/37026138-8d450f48-213e-11e8-894e-7556a18c39e6.png)

**Comment by pbelikov-gd** [comment]
Fixed. b9d0ed4e876f702cb942bde4d491b2de0d775b7c

**Comment by snovikov-gd** [comment]
Created [new issue](https://github.com/pbelikov-gd/gridu-js-lp-css/issues/24)
