### ISSUE TITLE
[Main Page] Fix margins between products

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#11]
Fix margins between products

![m6](https://user-images.githubusercontent.com/9034705/37026181-a4950f86-213e-11e8-9580-939c2b280490.png)

**Comment by pbelikov-gd** [comment]
Fixed, now it is 30px. b9d0ed4e876f702cb942bde4d491b2de0d775b7c

**Comment by snovikov-gd** [comment]
Confirmed
