### ISSUE TITLE
[Main Page] Remove box shadow on product hover/focus

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#12]
Remove box shadow on product hover/focus

![m7](https://user-images.githubusercontent.com/9034705/37026214-c170e12a-213e-11e8-82fa-dd347700f112.png)

**Comment by pbelikov-gd** [comment]
Box-shadow is removed. b9d0ed4e876f702cb942bde4d491b2de0d775b7c

**Comment by snovikov-gd** [comment]
Confirmed
