### ISSUE TITLE
[Global] Restrict width of header content block

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#13]
Restrict width of header content block

![m8a](https://user-images.githubusercontent.com/9034705/37026272-e8daa8e0-213e-11e8-9983-9496f4fe3617.png)

![m8b](https://user-images.githubusercontent.com/9034705/37026276-edcd0e1a-213e-11e8-8e7f-5ebbb6b804ba.png)

**Comment by pbelikov-gd** [comment]
Width is restricted, icons will not go wider then content panel. b9d0ed4e876f702cb942bde4d491b2de0d775b7c

**Comment by snovikov-gd** [comment]
Confirmed
