### ISSUE TITLE
[Main Page] Add pressed state for the filter button

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#14]
Filter buttom must be pressed when filter is opened.

![m1](https://user-images.githubusercontent.com/9034705/37026461-7dde52fc-213f-11e8-9a88-788a662adee5.png)

**Comment by pbelikov-gd** [comment]
State is added. b9d0ed4e876f702cb942bde4d491b2de0d775b7c

**Comment by snovikov-gd** [comment]
Confirmed
