### ISSUE TITLE
[Product Page] Increase font size 

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#15]
Increase font size 

![mx](https://user-images.githubusercontent.com/9034705/37027214-c94f6440-2141-11e8-9546-608b84a58431.png)

**Comment by pbelikov-gd** [comment]
Size increased. b9d0ed4e876f702cb942bde4d491b2de0d775b7c

**Comment by snovikov-gd** [comment]
Confirmed
