### ISSUE TITLE
[Product Page] Fix edit popup styles

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#16]
There are many differences: in width, fonts, margins, etc. Make it looking accoding to design.

![m0](https://user-images.githubusercontent.com/9034705/37027445-586e17fc-2142-11e8-978b-6176ad9ac516.png)

**Comment by pbelikov-gd** [comment]
Styles updated, now it look very close to mockup. de80371e8949ff152f67b79c7cc30b9f21add8cc

**Comment by snovikov-gd** [comment]
Confirmed
