### ISSUE TITLE
[Global] Blur background entirely when popup is opened

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#17]
Blur background entirely when popup is opened

![mm1](https://user-images.githubusercontent.com/9034705/37027617-ede6f98e-2142-11e8-8957-7b28d508bb66.png)

**Comment by pbelikov-gd** [comment]
Fixed. 8ff9ef9e090d81336d90169b20356ca67542dda2

**Comment by snovikov-gd** [comment]
Confirmed
