### ISSUE TITLE
[Product Page] Fix delete popup styles

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#18]
Fix delete popup styles according to design

![mm2](https://user-images.githubusercontent.com/9034705/37027732-38185e62-2143-11e8-96d7-fea995d142a2.png)

**Comment by pbelikov-gd** [comment]
Styles updated. de80371e8949ff152f67b79c7cc30b9f21add8cc

**Comment by snovikov-gd** [comment]
Created [new issue](https://github.com/pbelikov-gd/gridu-js-lp-css/issues/23)
