### ISSUE TITLE
[Product Page] Fix success popup styles

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#19]
Fix success popup styles according to design

![mm3](https://user-images.githubusercontent.com/9034705/37027824-7aa964e2-2143-11e8-8e04-858ccc4af6fc.png)

**Comment by pbelikov-gd** [comment]
Styles updated. de80371e8949ff152f67b79c7cc30b9f21add8cc

**Comment by snovikov-gd** [comment]
Confirmed
