### ISSUE TITLE
[Login Page] Fix incorrect heading font

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#2]
Fix incorrect heading font

![2](https://user-images.githubusercontent.com/9034705/37025630-46745930-213d-11e8-904d-0dcdb6de8c08.png)

**Comment by pbelikov-gd** [comment]
It is similar to one, that is in invision prototype (PT Sans Caption). It seems, that it was updated since prototype creation. Quotes will be updated though.

**Comment by pbelikov-gd** [comment]
Fixed quotes. 8ff9ef9e090d81336d90169b20356ca67542dda2

**Comment by snovikov-gd** [comment]
Confirmed
