### ISSUE TITLE
[Product Page] Fix issues

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#20]
Fix all the issues similar with the main page ones:

- [Fix incorrect title font](https://github.com/pbelikov-gd/gridu-js-lp-css/issues/8)
- [Fix separator style](https://github.com/pbelikov-gd/gridu-js-lp-css/issues/7)
- [Fix price block styles](https://github.com/pbelikov-gd/gridu-js-lp-css/issues/10)

**Comment by pbelikov-gd** [comment]
Fixed. b9d0ed4e876f702cb942bde4d491b2de0d775b7c

**Comment by snovikov-gd** [comment]
Created [new issue](https://github.com/pbelikov-gd/gridu-js-lp-css/issues/22)
