### ISSUE TITLE
[Global] Remove product_customer_with_review and product_customer_sold_out pages

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#21]
Remove product_customer_with_review and product_customer_sold_out as it is not part of HTML/CSS course requirements. It will be needed for the next, JavaScript course

![m1](https://user-images.githubusercontent.com/9034705/37028112-6a90cc02-2144-11e8-8f30-47a445b4461a.png)

![mmzz](https://user-images.githubusercontent.com/9034705/37028161-8a449af6-2144-11e8-8af1-904a069d6ddd.png)

**Comment by pbelikov-gd** [comment]
Out-of-scope items are moved out from build. 9b6b38d60d16ecbdc3fafce508be9c28b4559ae2

**Comment by snovikov-gd** [comment]
Confirmed
