### ISSUE TITLE
[Product Page] Make title and price bolder

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#22]
[Product Page] Make title and price bolder

![bold](https://user-images.githubusercontent.com/9034705/37094201-24bc7af2-2223-11e8-812f-ed175218c8a7.png)

**Comment by pbelikov-gd** [comment]
Fixed. c12b2757062869a33bfac7ff1a6a2733658720c1

**Comment by snovikov-gd** [comment]
Confirmed.
