### ISSUE TITLE
[Product Page] Make 'Cancel' button grey

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#23]
Make 'Cancel' button grey

![greyed](https://user-images.githubusercontent.com/9034705/37094328-a224a6ea-2223-11e8-8504-4142d89f5139.png)

**Comment by pbelikov-gd** [comment]
Applied "secondary" button style. c12b2757062869a33bfac7ff1a6a2733658720c1

**Comment by snovikov-gd** [comment]
Confirmed.
