### ISSUE TITLE
Do not use selector by tag name

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#25]
Get rid of styling elements using tag name like `footer { ... }` etc. Add classes for all the dom nodes, change theirs CSS selectors accordingly. 

It is useful practice that helps to not to lose control of CSS complexity in the future. Styling elements through classes you don't have to think much of CSS cascading and selectors specifity much. The best way is to use one of the existing CSS methodologies/naming conventions like [BEM](https://ru.bem.info/methodology/quick-start/). You don't need to refactor your code with BEM though it would be useful to read 'Quick Start' section there.

![1](https://user-images.githubusercontent.com/9034705/37283755-2910a8cc-260a-11e8-83e3-98742e0228b5.png)

**Comment by pbelikov-gd** [comment]
Fixed wherever found. c42665259d8bb19e162b6f7679024d920836c71c

**Comment by snovikov-gd** [comment]
Confirmed.
