### ISSUE TITLE
Delay javascript execution

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#26]
Since you don't have anything affecting markup rendering in your javascript files, that's a common practice to move all the `<script>` statements(bundle, jquery, etc) before closing `<body>` tag or add them `defer` attribute. 

It will make rendering and displaying HTML/CSS before scripts execution possible.

**Comment by pbelikov-gd** [comment]
Legal bug it is: all scripts were ran at the very end (positioned in the bottom of `<body>` tag, but bundle was duplicated on top. Will be removed.

**Comment by pbelikov-gd** [comment]
Fixed. 5cbe4977aae03a61fecb1d52e8c56d7722c08d78

**Comment by snovikov-gd** [comment]
Confirmed.
