### ISSUE TITLE
Get rid of unnecessary <div>

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#27]
Get rid of unnecessary <div>

![2](https://user-images.githubusercontent.com/9034705/37285263-99c0edd4-260f-11e8-866f-a62c29740129.png)

**Comment by pbelikov-gd** [comment]
Fixed. c42665259d8bb19e162b6f7679024d920836c71c

**Comment by snovikov-gd** [comment]
Mainly fixed, confirmed.
