### ISSUE TITLE
Get rid of inline styles

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#28]
Get rid of inline styles. In the most cases using inline styles is antipattern.

![3](https://user-images.githubusercontent.com/9034705/37285353-d7a5c980-260f-11e8-8064-ea1bc19e17fc.png)

**Comment by pbelikov-gd** [comment]
Fixed. b948143e999bd876126e8eb39400643c2082f7f0

**Comment by snovikov-gd** [comment]
Confirmed.
