### ISSUE TITLE
Use shorthands for 'background' property

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#29]
It's more readable when background is written in one line, like `background: url("../images/modal-bg.png") repeat #d4d4d4` for this example.

![4](https://user-images.githubusercontent.com/9034705/37285452-14f767b2-2610-11e8-91aa-66f8f91b7d26.png)

**Comment by pbelikov-gd** [comment]
Fixed. c42665259d8bb19e162b6f7679024d920836c71c

**Comment by snovikov-gd** [comment]
Confirmed.
