### ISSUE TITLE
[Login Page] Fix incorrect icon size and alignment

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#3]
![3](https://user-images.githubusercontent.com/9034705/37025668-6140b970-213d-11e8-9d44-bcbd68701a37.png)

**Comment by pbelikov-gd** [comment]
Fixed. 8ff9ef9e090d81336d90169b20356ca67542dda2

**Comment by snovikov-gd** [comment]
Confirmed
