### ISSUE TITLE
Get rid of SVG duplication

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#30]
When using inline SVG you're duplicating DOM nodes for identical images. Put them to `star-inactive.svg` and `star-active.svg` files and use `<img>` instead.

![5](https://user-images.githubusercontent.com/9034705/37285738-006dce0c-2611-11e8-8a4f-445a19bf142e.png)

**Comment by pbelikov-gd** [comment]
Done. c42665259d8bb19e162b6f7679024d920836c71c

**Comment by snovikov-gd** [comment]
Confirmed.
