### ISSUE TITLE
Use heading tag for modal header

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#31]
Use `<h*>` tag for modal header instead of anonymous `div` as for now.

![6](https://user-images.githubusercontent.com/9034705/37285871-7333d562-2611-11e8-9050-9098c17a8251.png)

**Comment by pbelikov-gd** [comment]
Done. c42665259d8bb19e162b6f7679024d920836c71c

**Comment by snovikov-gd** [comment]
Mainly fixed, confirmed.
