### ISSUE TITLE
[Login Page] Blur and lighten page background

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#4]
Blur and lighten page background

![4](https://user-images.githubusercontent.com/9034705/37025707-7dba5fde-213d-11e8-9ed7-9a3b956e79eb.png)

**Comment by pbelikov-gd** [comment]
Fixed. 8ff9ef9e090d81336d90169b20356ca67542dda2

**Comment by snovikov-gd** [comment]
Confirmed
