### ISSUE TITLE
[Login Page] Fix valid input styles

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#5]
Fix valid input styles

![5](https://user-images.githubusercontent.com/9034705/37025780-a4379fd2-213d-11e8-8300-25f7ccf6a512.png)

**Comment by pbelikov-gd** [comment]
Fixed. 8ff9ef9e090d81336d90169b20356ca67542dda2

**Comment by snovikov-gd** [comment]
Confirmed
