### ISSUE TITLE
[Main Page] Fix product title font

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#8]
Fix product title font

![m3](https://user-images.githubusercontent.com/9034705/37025930-063285a8-213e-11e8-95aa-9e78598b167f.png)

**Comment by pbelikov-gd** [comment]
It is PT Sans.

**Comment by pbelikov-gd** [comment]
Font does not seem to be different: size is same, family is same, weight is same.

**Comment by snovikov-gd** [comment]
It must be 'PT Sans' bold, I see you added `font-weight: bold` but it doesn't work. Created [new issue](https://github.com/pbelikov-gd/gridu-js-lp-css/issues/24)
