### ISSUE TITLE
[Main Page] Fix price block and 'Show more' alignment

### ISSUE THREAD

**Issue by snovikov-gd** [pbelikov-gd/gridu-js-lp-css#9]
Fix price block and 'Show more' alignment. They must be always at the bottom of a product block.

![m4](https://user-images.githubusercontent.com/9034705/37026000-370a5598-213e-11e8-94fd-0770da6b0752.png)

**Comment by pbelikov-gd** [comment]
Fixed. b9d0ed4e876f702cb942bde4d491b2de0d775b7c

**Comment by snovikov-gd** [comment]
Confirmed
